spring:
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/shoppingmall?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME:mallAdmin}
    password: ${DB_PASSWORD:qwe123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.security: DEBUG
    org.springframework.security.authentication: TRACE
    org.springframework.data.elasticsearch: DEBUG

file:
  upload-path: ${FILE_UPLOAD_PATH:/upload/images/}
  access-url: ${FILE_ACCESS_URL:/images/}

flask:
  base-url: http://flask:5000