apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: elasticsearch-pvc
  name: elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: elasticsearch-pv
  storageClassName: ""  # 명시적으로 none
