apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-monitor
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: flask
  endpoints:
    - port: "5000"
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
