kraft:
  enabled: false

zookeeper:
  enabled: true

listeners:
  client:
    protocol: PLAINTEXT
    port: 9092

advertisedListeners:
  client:
    - PLAINTEXT://kafka:9092

metrics:
  kafka:
    enabled: true

  jmx:
    enabled: true

serviceMonitor:
  enabled: true
