grafana:
  service:
    type: LoadBalancer
    port: 3000
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false
      jsonData: { }
      version: 1
prometheus:
  service:
    type: LoadBalancer
    servicePort: 9090